###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22291 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22291"
      rule_id="SV-26303r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system must use at least two time sources for clock synchronization.</title>
      <discussion>A synchronized system clock is critical for the enforcement of time-based policies and the correlation of logs and audit records with other systems.  For redundancy, two time sources are required so synchronization continues to function if one source fails.  

      If the system is completely isolated (no connections to networks or other systems), time synchronization is not required as no correlation of events or operation of time-dependent protocols between systems will be necessary.  If the system is completely isolated, this requirement is not applicable.

      NOTE:  For the Network Time Protocol (NTP), the requirement is two servers, but it is recommended to configure at least four distinct time servers which allow NTP to effectively exclude a time source not consistent with the others.  The system's local clock must be excluded from the count of time sources.</discussion>
      <check_content>Determine the zone that you are currently securing.

      # zonename

      If the command output is not "global", this is not applicable.

      Check the NTP daemon configuration for at least two external servers.
      # grep '^server' /etc/inet/ntp.conf | egrep -v '(127.127.1.1|127.127.1.0)'
      If less than two servers or external reference clocks (127.127.x.x other than 127.127.1.0 or 127.127.1.1) are listed, this is a finding.</check_content>
      <fix_text>Add an additional server line to /etc/inet/ntp.conf for each additional NTP server.</fix_text>

- name: V-22291 Check
  shell: "if [ `zonename` = 'global' ];   then grep '^server' /etc/inet/ntp.conf | egrep -v '(127.127.1.1|127.127.1.0)';   else echo This is a zone and not applicable `zonename`; fi"
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22291 Check 2
  shell: "if [ `zonename` = 'global' ];   then grep '^server' /etc/inet/ntp.conf | egrep -v '(127.127.1.1|127.127.1.0)' | wc -l |awk '$1 > 1';   else echo This is a zone and not applicable `zonename`; fi "
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22291 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22291
      The system must use at least two time sources for clock synchronization.
      If the command output is not "global", this is not applicable.
      If less than two servers or external reference clocks (127.127.x.x other than 127.127.1.0 or 127.127.1.1) are listed, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>Two external servers are configured for NTP</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000160</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" and REPORT == 1)

- name: V-22291 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22291
      The system must use at least two time sources for clock synchronization.
      If the command output is not "global", this is not applicable.
      If less than two servers or external reference clocks (127.127.x.x other than 127.127.1.0 or 127.127.1.1) are listed, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>Two external servers are configured for NTP</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000160</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout == ""

- name: V-22291 Fix-1
  lineinfile: dest=/etc/inet/ntp.conf state=present regexp=pxntp4 line="server pxntp4"
  ignore_errors: True
  when: (checkmyconf2.stdout == "" and FIX == 1)
 
- name: V-22291 Fix-2
  lineinfile: dest=/etc/inet/ntp.conf state=present regexp=pxntp3 line="server pxntp3"
  ignore_errors: True
  when: (checkmyconf2.stdout == "" and FIX == 1)
