###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22365 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22365"
      rule_id="SV-39902r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All shell files must be group-owned by root, bin, or sys.</title>
      <discussion>If shell files are group-owned by users other than root or a system group, they could be modified by intruders or malicious users to perform unauthorized actions.</discussion>
      <check_content>If /etc/shells exists, check the group ownership of each shell referenced.

      Procedure:
      # cat /etc/shells | xargs -n1 ls -lL

      Otherwise, check any shells found on the system.
      Procedure:
      # find / -name "*sh" | xargs -n1 ls -lL

      If a shell is not group-owned by root, bin, or sys, this is a finding.</check_content>
      <fix_text>Change the group-owner of the shell to root, bin, or sys.

      Procedure:
      # chgrp root &lt;shell&gt;</fix_text>

- name: V-22365 Check
  shell: cat /etc/shells | xargs -n1 ls -lL
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22365 Check 2
  shell: cat /etc/shells | xargs -n1 ls -lL | awk '$4 !~ /root|bin|sys/ | $1 !~ /\+/ {print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22365 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22365 
      All shell files must be group-owned by root, bin, or sys.
      If a shell is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>Shells are group owned by root</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22365 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22365 
      All shell files must be group-owned by root, bin, or sys.
      If a shell is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>Shells are NOT group owned by root</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22365 Fix-1
  file: path="{{item}}" group=root mode=0755 state=file
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
