###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-781 Check
  shell: logins -o | awk "-F:" '$3 == ""'
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-781 Check 2
  shell: logins -o | awk "-F:" '$3 == ""'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-781 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-781"
      rule_id="SV-27069r1_rule"
      raw_risk="III"
      datetime="{{ ansible_date_time.date }}">
      <title>All GIDs referenced in the /etc/passwd file must be defined in the /etc/group file.</title>
      <discussion>If a user is assigned the GID of a group not existing on the system, and a group with the same GID is subsequently created, the user may have unintended rights to the group.
      </discussion>
      <check_content>Perform the following to ensure there are no GIDs referenced in /etc/passwd not defined in /etc/group.
      # logins -o | awk -F: '$3 == ""'
      If any lines are returned, there are GIDs referenced in /etc/passwd that are not defined in /etc/group, this is a finding.</check_content>
      <fix_text>Add a group to the system for each GID referenced that does not have a corresponding group. 

      #/usr/sbin/groupadd &lt; group &gt;</fix_text>  

- name: V-781 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # logins -o | awk "-F:" '$3 == ""'
      </procedure>
      <output>
      V-781
      All GIDs referenced in the /etc/passwd file must be defined in the /etc/group file.
      If any lines are returned, there are GIDs referenced in /etc/passwd that are not defined in /etc/group, this is a finding.
      Procedure:
      # logins -o | awk "-F:" '$3 == ""'
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>All GIDs in /etc/passwd are defined in /etc/group</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
      </finding>
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-781 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # logins -o | awk "-F:" '$3 == ""'
      </procedure>
      <output>
      V-781
      All GIDs referenced in the /etc/passwd file must be defined in the /etc/group file.
      If any lines are returned, there are GIDs referenced in /etc/passwd that are not defined in /etc/group, this is a finding.
      Procedure:
      # logins -o | awk "-F:" '$3 == ""'
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>Not All GIDs in /etc/passwd are defined in /etc/group</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
      </finding>
  when: checkmyconf1.stdout != ""
