###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-12030 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-12030"
      rule_id="SV-41532r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system's access control program must be configured to grant or deny system access to specific hosts.</title>
      <discussion>If the system's access control program is not configured with appropriate rules for allowing and denying access to system network resources, services may be accessible to unauthorized hosts.</discussion>
      <check_content>Check for the existence of the /etc/hosts.allow and /etc/hosts.deny files.

      Procedure:
      # ls -la /etc/hosts.allow
      # ls -la /etc/hosts.deny

      If either file does not exist, this is a finding.

      Check for the presence of a default deny entry.

      Procedure:
      # grep "ALL: ALL" /etc/hosts.deny

      If the "ALL: ALL" entry is not present in the /etc/hosts.deny file, any TCP service from a host or network not matching other rules will be allowed access.  If the entry is not in /etc/hosts.deny, this is a finding.</check_content>
      <fix_text>Edit the /etc/hosts.allow and /etc/hosts.deny files to configure access restrictions.
      </fix_text>

- name: V-12030 Check
  shell: "ls -la /etc/hosts.allow /etc/hosts.deny; awk '/ALL: ALL/' /etc/hosts.deny "
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-12030 Check 2
  shell: "awk '/ALL: ALL/' /etc/hosts.deny"
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False
 
- name: V-12030 Check 3
  shell: ls -la /etc/hosts.allow /etc/hosts.deny | wc -l
  args:
    executable: /bin/bash
  register: checkmyconf3
  ignore_errors: True
  changed_when: False


- name: V-12030 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-12030
      The system's access control program must be configured to grant or deny system access to specific hosts.
      If either /etc/hosts.allow or /etc/hosts.deny do not exist, this is a finding.
      If the "ALL: ALL" entry is not present in the /etc/hosts.deny file this is a finding.


      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>/etc/hosts.allow and /etc/hosts.deny exist</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" and checkmyconf3.stdout == "       2" and REPORT == 1)

- name: V-12030 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-12030
      The system's access control program must be configured to grant or deny system access to specific hosts.
      If either /etc/hosts.allow or /etc/hosts.deny do not exist, this is a finding.
      If the "ALL: ALL" entry is not present in the /etc/hosts.deny file this is a finding.


      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>/etc/hosts.allow or /etc/hosts.deny do not exist</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
      </finding>
  when: ( checkmyconf2.stdout == "" or checkmyconf3.stdout != "       2" )
