###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22356 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22356"
      rule_id="SV-26471r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All global initialization files must not have extended ACLs.</title>
      <discussion>Global initialization files are used to configure the user's shell environment upon login.  Malicious modification of these files could compromise accounts upon logon.</discussion>
      <check_content>Check global initialization files for extended ACLs.
      # ls -lL /etc/profile /etc/bashrc /etc/csh.login /etc/csh.cshrc /etc/environment /etc/.login /etc/security/environ
      If the permissions on an existing file include a "+", the file has an extended ACL, this is a finding.</check_content>
      <fix_text>Remove the extended ACL from the file.
      # chmod A- [global initialization file with extended ACL]</fix_text>

- name: V-22356 Check
  shell: ls -lL /etc/profile /etc/bashrc /etc/csh.login /etc/csh.cshrc /etc/environment /etc/.login /etc/security/environ /etc/skel 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22356 Check 2
  shell: ls -lL /etc/profile /etc/bashrc /etc/csh.login /etc/csh.cshrc /etc/environment /etc/.login /etc/security/environ /etc/skel 2>/dev/null | awk '/\+/ {print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22356 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output>    
      V-22356 
      All global initialization files must not have extended ACLs.
      If the permissions on an existing file include a "+", the file has an extended ACL, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>No extended ACLs were found in /etc/profile /etc/bashrc /etc/csh.login /etc/csh.cshrc /etc/environment /etc/.login /etc/security/environ</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22356 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output>    
      V-22356 
      All global initialization files must not have extended ACLs.
      If the permissions on an existing file include a "+", the file has an extended ACL, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>Extended ACLs were found in /etc/profile /etc/bashrc /etc/csh.login /etc/csh.cshrc /etc/environment /etc/.login /etc/security/environ</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22356 Fix-1
  shell:  chmod A- "{{item}}"
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
