###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22303 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22303"
      rule_id="SV-40776r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system must use a FIPS 140-2 approved cryptographic hashing algorithm for generating account password hashes.</title>
      <discussion>Systems must employ cryptographic hashes for passwords using the SHA-2 family of algorithms or FIPS 140-2 approved successors. The use of unapproved algorithms may result in weak password hashes more vulnerable to compromise.</discussion>
      <check_content>Verify the traditional UNIX crypt algorithm is deprecated.
      # egrep CRYPT_ALGORITHMS_ALLOW /etc/security/policy.conf
      If CRYPT_ALGORITHMS_ALLOW is not set, is not set to "6", or is not set to "5,6", this is a finding.

      Verify new password hashes are generated using either the SHA-256 or SHA-512 cryptographic hashing algorithm.
      # egrep CRYPT_DEFAULT /etc/security/policy.conf
      If CRYPT_DEFAULT is not set or is not equal to 5 or 6, this is a finding.</check_content>
      <fix_text>Edit the /etc/security/policy.conf file.
      # vi /etc/security/policy.conf
      Uncomment or add the CRYPT_ALGORITHMS_ALLOW line and set it to "5,6". Update the CRYPT_DEFAULT default line to be equal to 5 or 6. The following lines are acceptable.

      CRYPT_ALGORITHMS_ALLOW=5,6
      CRYPT_DEFAULT=6</fix_text>


- name: V-22303 Check
  shell: egrep CRYPT_ALGORITHMS_DEPRECATE /etc/security/policy.conf 2>&1; egrep CRYPT_DEFAULT /etc/security/policy.conf 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22303 Check 2
  shell: awk '/CRYPT_ALGORITHMS_DEPRECATE/ && !/^#/' /etc/security/policy.conf
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22303 Check 3
  shell: awk '/CRYPT_DEFAULT=5|CRYPT_DEFAULT=6/ && !/^#/' /etc/security/policy.conf
  register: checkmyconf3
  ignore_errors: True
  changed_when: False

- name: V-22303 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22303
      The system must use a FIPS 140-2 approved cryptographic hashing algorithm for generating account password hashes.
      If CRYPT_ALGORITHMS_DEPRECATE is not set or does not include "__unix__", this is a finding. 
      If CRYPT_DEFAULT is not set or is not equal to 5 or 6, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>/etc/security/policy.conf is configured as needed</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000803</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" and REPORT == 1)

- name: V-22303 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22303
      The system must use a FIPS 140-2 approved cryptographic hashing algorithm for generating account password hashes.
      If CRYPT_ALGORITHMS_DEPRECATE is not set or does not include "__unix__", this is a finding. 
      If CRYPT_DEFAULT is not set or is not equal to 5 or 6, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>/etc/security/policy.conf is NOT configured as needed</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000803</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout == ""

- name: V-22303 Fix-1
  lineinfile: dest=/etc/security/policy.conf state=present regexp=CRYPT_ALGORITHMS_DEPRECATE line="CRYPT_ALGORITHMS_DEPRECATE=__unix__,1,2a,md5"
  ignore_errors: True
  when: (checkmyconf2.stdout == "" and FIX == 1)

- name: V-22303 Fix-2
  lineinfile: dest=/etc/security/policy.conf state=present regexp=CRYPT_DEFAULT line="CRYPT_DEFAULT=6"
  ignore_errors: True
  when: (checkmyconf3.stdout == "" and FIX == 1)
