###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-12765 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-12765"
      rule_id="SV-28461r4_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system must use and update a DoD-approved virus scan program.</title>
      <discussion>Virus scanning software can be used to protect a system from penetration from computer viruses and to limit their spread through intermediate systems.  Virus scanning software is available to DoD on the JTF-GNO web site.

      The virus scanning software should be configured to perform scans dynamically on accessed files.  If this capability is not available, the system must be configured to scan, at a minimum, all altered files on the system on a daily basis.

      If the system processes inbound SMTP mail, the virus scanner must be configured to scan all received mail.</discussion>
      <check_content>Check for the existence of the McAfee command line scan tool to be executed daily in the cron file.  Additional tools specific for each operating system are also available and will have to be manually reviewed if installed.  In addition, the definitions file should not be older than seven (7) days.

      Check if uvscan is scheduled to run.
      # grep uvscan /var/spool/cron/crontabs/*

      Perform the following command to ensure the virus definition signature files are not older than seven (7) days.

      # ls -la avvclean.dat avvnames.dat avvscan.dat

      If a virus scanner is not being run daily or the virus definitions are older than seven (7) days, this is a finding.</check_content>
      <fix_text>Install McAfee command line virus scan tool, or an appropriate alternative from https://www.jtfgno.mil.

      Ensure the virus signature definition files are no older than seven (7) days.

      Updates are also available from https://www.jtfgno.mil.

      Ensure the command line virus scan tool is run on a regular basis using a utility, such as cron.</fix_text>

- name: V-12765 Check
  shell: crontab -l | awk '/uvscan/'
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-12765 Check 2
  shell: crontab -l | awk '/uvscan/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-12765 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-12765
      The system must use and update a DoD-approved virus scan program. 
      If a virus scanner is not being run daily or the virus definitions are older than seven (7) days, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>Uvscan runs from cron and virus definitions are up to date</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-001668</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" and REPORT == 1)

- name: V-12765 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-12765
      The system must use and update a DoD-approved virus scan program. 
      If a virus scanner is not being run daily or the virus definitions are older than seven (7) days, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>Uvscan does not runs from cron and virus definitions are not up to date</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-001668</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout == ""

- name: V-12765 Fix-1
  shell:  "(crontab -l;echo '#### uvscan ####') | crontab;  (crontab -l;echo '0 2 * * * job=/usr/lbin/uvscan-excluding-nfs; if [ -f  ];then  ;fi') | crontab"
  ignore_errors: True
  when: (checkmyconf2.stdout == "" and FIX == 1)
