###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22358 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22358"
      rule_id="SV-39901r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All skeleton files (typically in /etc/skel) must be group-owned by root, bin, or sys.</title>
      <discussion>If the skeleton files are not protected, unauthorized personnel could change user startup parameters and possibly jeopardize user files.</discussion>
      <check_content>Verify the skeleton files are group-owned by root, bin, or sys.

      Procedure:
      # ls -alL /etc/skel

      If a skeleton file is not group-owned by root, bin, or sys, this is a finding.</check_content>
      <fix_text>Change the group owner of the skeleton file to root.

      Procedure:
      # chgrp &lt;group&gt; /etc/skel/[skeleton file]   </fix_text>

- name: V-22358 Check
  shell: ls -lL /etc/skel 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22358 Check 2
  shell: ls -lL /etc/skel 2>/dev/null | awk '/\+/ {print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22358 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output>    
      V-22358 
      All skeleton files (typically in /etc/skel) must be group-owned by root, bin, or sys.
      If a skeleton file is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>All files in /etc/skel are group owned by root</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22358 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output>    
      V-22358 
      All skeleton files (typically in /etc/skel) must be group-owned by root, bin, or sys.
      If a skeleton file is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>All files in /etc/skel are NOT group owned by root</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22358 Fix-1
  shell:  chmod A- "{{item}}"
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
