###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22397 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22397"
      rule_id="SV-26570r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The at.allow file must be group-owned by root, bin, or sys.</title>
      <discussion>If the group owner of the at.allow file is not set to root, bin, or sys, unauthorized users could be allowed to view or edit the list of users permitted to run at jobs.  Unauthorized modification could result in Denial of Service to authorized at users or provide unauthorized users with the ability to run at jobs.</discussion>
      <check_content>Check the group ownership of the file.

      Procedure:
      # ls -lL /etc/cron.d/at.allow

      If the file is not group-owned by root, bin, or sys, this is a finding.</check_content>
      <fix_text>Change the group ownership of the file.

      Procedure:
      # chgrp root /etc/cron.d/at.allow</fix_text>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>


- name: V-22397 Check
  shell: ls -lLd /var/spool/cron/at.allow 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22397 Check 2
  shell: ls -lLd /var/spool/cron/at.allow | awk '$4 !~ /root|bin|sys/ {print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22397 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22397
      The "at" directory must be group-owned by root, bin, or sys.
      If the "at" directory is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>/etc/cron.d/at.allow is group-owned by root</comments>
      <status>Not a Finding</status>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22397 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22397
      The "at" directory must be group-owned by root, bin, or sys.
      If the "at" directory is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>/etc/cron.d/at.allow is NOT group-owned by root</comments>
      <status>Ongoing</status>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22397 Fix-1
  file: path="{{item}}" group=sys state=directory
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
