###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-12024 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-12024"
      rule_id="SV-41525r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system must not have a public Instant Messaging (IM) client installed.</title>
      <discussion>Public Instant Messaging (IM) systems are not approved for use and may result in the unauthorized distribution of information. IM clients provide a way for a user to send a message to one or more other users in real time. Additional capabilities may include file transfer and support for distributed game playing. Communication between clients and associated directory services are managed through messaging servers. Commercial IM clients include AOL Instant Messenger (AIM), MSN Messenger, and Yahoo! Messenger.

      IM clients present a security issue when the clients route messages through public servers. The obvious implication is potentially sensitive information could be intercepted or altered in the course of transmission. This same issue is associated with the use of public email servers. In order to reduce the potential for disclosure of sensitive Government information and to ensure the validity of official government information, IM clients connecting to public IM services will not be installed. Clients used to access internal or DoD-controlled IM services are permitted.</discussion>
      <check_content>If an IM client is installed, ask the SA if it has access to any public domain IM servers.  If it does have access to public servers, this is a finding.

      </check_content>
      <fix_text>Uninstall the IM client from the system, or configure the client to only connect to DoD-approved IM services.
      </fix_text>

- name: V-12024 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      #  ]]>
      </procedure>
      <output> 
      V-12024
      The system must not have a public Instant Messaging (IM) client installed.
      If an IM client is installed, ask the SA if it has access to any public domain IM servers. If it does have access to public servers, this is a finding. 

      No IM clients were found to be installed on this system. 
      
      -
      This is NOT a finding
      -
      </output>
      <comments>Comments go here </comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000366</cci>
      <cci>CCI-001154</cci>
      </ccis>
      </finding>