###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22424 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22424"
      rule_id="SV-26653r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The inetd.conf file must not have extended ACLs.</title>
      <discussion>The Internet service daemon configuration files must be protected as malicious modification could cause Denial of Service or increase the attack surface of the system.</discussion>
      <check_content>Check the permissions of the inetd configuration file.
      # ls -lL /etc/inet/inetd.conf
      If the permissions include a "+", the file has an extended ACL and this is a finding.</check_content>
      <fix_text>Remove the extended ACL from the file.
      # chmod A- /etc/inet/inetd.conf</fix_text>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>

- name: V-22424 Check
  shell: ls -lL /etc/inet/inetd.conf
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22424 Check 2
  shell: ls -lL /etc/inet/inetd.conf | awk '/\+/'
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22424 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22424
      The inetd.conf file must not have extended ACLs.
      If the permissions include a "+", the file has an extended ACL and this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>no extended ACLs are configured on /etc/inet/inetd.conf</comments>
      <status>Not a Finding</status>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22424 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22424
      The inetd.conf file must not have extended ACLs.
      If the permissions include a "+", the file has an extended ACL and this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>Extended ACLs are configured on /etc/inet/inetd.conf</comments>
      <status>Ongoing</status>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22424 Fix-1
  shell:  chmod A- /etc/inet/inetd.conf
  args:
    executable: /bin/bash
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
