###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22335 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22335"
      rule_id="SV-26431r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The /etc/group file must be owned by root.</title>
      <discussion>The /etc/group file is critical to system security and must be owned by a privileged user.  The group file contains a list of system groups and associated information.</discussion>
      <check_content>Verify the /etc/group file is owned by root.

      Procedure:
      # ls -l /etc/group
      If the file is not owned by root, this is a finding.</check_content>
      <fix_text>Change the owner of the /etc/group file to root.

      # chown root /etc/group</fix_text>

- name: V-22335 Check
  shell: ls -l /etc/group
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22335 Check 2
  shell: ls -l /etc/group | awk '$1 ~ /\+/ || $3 !~ /root/ || $4 !~ /root|bin|sys/ {print $9}'
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22335 Check 3
  stat: path=/etc/group
  register: checkmyconf3
  ignore_errors: True
  changed_when: False


- name: V-22335 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22335 
      The /etc/group file must be owned by root.

      If the file is not owned by root, this is a finding.
      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>/etc/group is owned by root</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22335 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22335 
      The /etc/group file must be owned by root.

      If the file is not owned by root, this is a finding.
      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>/etc/group is owned by root</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" )

- name: V-22335 Fix-1
  file: path=/etc/group group=root owner=root mode=0644 state=file
  ignore_errors: True
  #when: (checkmyconf2.stdout != "" and FIX == 1)

