###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22324 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22324"
      rule_id="SV-39896r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The /etc/hosts file must be group-owned by root, bin, or sys.</title>
      <discussion>The /etc/hosts file (or equivalent) configures local host name to IP address mappings that typically take precedence over DNS resolution.  If this file is maliciously modified, it could cause the failure or compromise of security functions requiring name resolution, which may include time synchronization, centralized authentication, and remote system logging.</discussion>
      <check_content>Check the /etc/hosts file's group ownership.

      Procedure:
      # ls -lL /etc/hosts

      If the file is not group-owned by root, bin, or sys, this is a finding.</check_content>
      <fix_text>Change the group owner of the /etc/hosts file to root, sys, or bin.

      Procedure:
      # chgrp root /etc/hosts</fix_text>  

- name: V-22324 Check
  shell: ls -lL /etc/hosts
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22324 Check-2
  shell: ls -lL /etc/hosts | awk '$4 !~ /root|bin|sys/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22324 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22324
      The /etc/hosts file must be group-owned by root, bin, or sys.
      If the file is not group-owned by root, bin, or sys, this is a finding.
      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>/etc/hosts is group owned by root</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>

  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22324 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22324
      The /etc/hosts file must be group-owned by root, bin, or sys.
      If the file is not group-owned by root, bin, or sys, this is a finding.
      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>/etc/hosts is NOT group owned by root</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22324 Fix
  file: path=/etc/hosts group=root owner=root mode=0644
  when: (checkmyconf2.stdout != "" and FIX == 1)
