###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-785 Check
  shell: ls / | while read DIR; do find /$DIR  -fstype nfs -prune -o -fstype objfs -prune -o -fstype proc -prune -type f  -name .forward -print >> /root/find.4385 ; done
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-785 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-785"
      rule_id="SV-785r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All files and directories must have a valid owner.</title>
      <discussion>Unowned files and directories may be unintentionally inherited if a user is assigned the same UID as the UID of the unowned files.</discussion>
      <check_content>Check the system for files with no assigned owner.

      Procedure:
      # find / -nouser -print

      If any files have no assigned owner, this is a finding.</check_content>
      <fix_text>All directories and files (executable and data) will have an identifiable owner and group name. Either trace files to an authorized user, change the file's owner to root, or delete them. Determine the legitimate owner of the files and use the chown command to set the owner and group to the correct value. If the legitimate owner cannot be determined, change the owner to root (but make sure none of the changed files remain executable because they could be Trojan horses or other malicious code). Examine the files to determine their origin and the reason for their lack of an owner/group.</fix_text>


- name: V-785 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
        Procedure: 
        # find / -nouser  -exec ls -ld {} \;
      </procedure>
      <output>
      V-785
      All files and directories must have a valid owner.
      If any files have no assigned owner, this is a finding.
      Procedure:
      # find / -nouser  -exec ls -ld {} \;
      OUTPUT:
      #->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>no files have no assigned owner</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
      </finding>
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-785 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
        Procedure: 
        # find / -nouser  -exec ls -ld {} \;
      </procedure>
      <output>
      V-785
      All files and directories must have a valid owner.
      If any files have no assigned owner, this is a finding.
      Procedure:
      # find / -nouser  -exec ls -ld {} \;
      OUTPUT:
      #->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>Some files have no assigned owner</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
  when: checkmyconf1.stdout != ""
