###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-12019 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-12019"
      rule_id="SV-40274r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The snmpd.conf files must be owned by root.</title>
      <discussion>The snmpd.conf files contain authenticators and must be protected from unauthorized access and modification.  If the files are not owned by root, they may be subject to access and modification from unauthorized users.</discussion>
      <check_content>Determine the owner of the SNMP configuration files. 

      Procedure:

      # ls -lL /etc/sma/snmp/snmpd.conf /etc/snmp/conf/snmpd.conf /var/sma_snmp/snmpd.conf /usr/sfw/lib/sma_snmp/snmpd.conf

      If the snmpd.conf files are not owned by root, this is a finding.</check_content>
      <fix_text>Change the owner of the snmpd.conf file to root.

      Procedure:
      # chown root &lt;snmpd.conf file&gt; </fix_text>    

- name: V-12019 Check
  shell: ls -lL /etc/sma/snmp/snmpd.conf /etc/snmp/conf/snmpd.conf /var/sma_snmp/snmpd.conf /usr/sfw/lib/sma_snmp/snmpd.conf 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-12019 Check 2
  shell: ls -lL /etc/sma/snmp/snmpd.conf /etc/snmp/conf/snmpd.conf /var/sma_snmp/snmpd.conf /usr/sfw/lib/sma_snmp/snmpd.conf 2>/dev/null | awk '$3 !~ /root/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-12019 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
        V-12019
      The snmpd.conf files must be owned by root.
      If the snmpd.conf files are not owned by root, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>snppd.conf files are owned by root</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-12019 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
        V-12019
      The snmpd.conf files must be owned by root.
      If the snmpd.conf files are not owned by root, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>snppd.conf files are NOT owned by root</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-12019 Fix-1
  file: path="{{item}}" owner=root state=file
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
