###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22315 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22315"
      rule_id="SV-26369r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>System log files must not have extended ACLs, except as needed to support authorized software.</title>
      <discussion>If the system log files are not protected, unauthorized users could change the logged data, eliminating its forensic value.  Authorized software may be given log file access through the use of extended ACLs when needed and configured to provide the least privileges required.</discussion>
      <check_content>Verify all system log files have no extended ACLs.

      Procedure: 
      # ls -lL /var/adm 
      If the permissions include a "+", the file has an extended ACL. If an extended ACL exists, verify with the SA if the ACL is required to support authorized software and provides the minimum necessary permissions. If an extended ACL exists that provides access beyond the needs of authorized software, this is a finding.</check_content>
      <fix_text>Remove the extended ACL from the file.
      # chmod A- [file with extended ACL]</fix_text>

- name: V-22315 Check
  shell: ls -lL /var/adm 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22315 Check 2
  shell: ls -lL /var/adm | awk '$1 ~ /\+/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22315 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22315
      System log files must not have extended ACLs, except as needed to support authorized software.
      If an extended ACL exists that provides access beyond the needs of authorized software, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There are no ACLs in /var/adm </comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-001314</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22315 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22315
      System log files must not have extended ACLs, except as needed to support authorized software.
      If an extended ACL exists that provides access beyond the needs of authorized software, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>There are ACLs in /var/adm </comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-001314</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22315 Fix-1
  shell:  chmod A- "{{item}}"
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
