###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-11981 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-11981"
      rule_id="SV-39829r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All global initialization files must have mode 0644 or less permissive.</title>
      <discussion>Global initialization files are used to configure the user's shell environment upon login.  Malicious modification of these files could compromise accounts upon logon.</discussion>
      <check_content>Check global initialization files permissions.

      # ls -l /etc/.login
      # ls -l /etc/profile
      # ls -l /etc/bashrc
      # ls -l /etc/environment
      # ls -l /etc/security/environ
      # ls -l /etc/csh.login 
      # ls -l /etc/csh.cshrc

      If global initialization files exist and are more permissive than 0644, this is a finding.</check_content>
      <fix_text>Change the mode of the global initialization file(s) to 0644.
      # chmod 0644 &lt;global initialization file&gt;</fix_text>


- name: V-11981 Check
  shell: ls -ld /etc/.login /etc/profile /etc/bashrc /etc/environment /etc/security/environ /etc/csh.login /etc/csh.cshrc 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-11981 Check 2
  shell: find /etc/.login /etc/profile /etc/bashrc /etc/environment /etc/security/environ /etc/csh.login /etc/csh.cshrc \( -perm -0645 -a ! -perm -1777 \) -print 2>/dev/null
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-11981 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-11981
      All global initialization files must have mode 0644 or less permissive.
      If global initialization files exist and are more permissive than 0644, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There are no global initializationfiles more permissive than 0644</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-11981 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-11981
      All global initialization files must have mode 0644 or less permissive.
      If global initialization files exist and are more permissive than 0644, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>There are global initializationfiles more permissive than 0644</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-11981 Fix-1
  file: path="{{item}}" mode=0644 state=file
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
