###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-789 Check
  shell: ls -lRa /usr/lib/netsvc/yp /var/yp
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-789 Check 2
  shell: find /usr/lib/netsvc/yp /var/yp -exec ls -ld {} \; | awk '$3 !~ /root|sys|bin/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-789 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-789"
      rule_id="SV-27166r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>NIS/NIS+/yp files must be owned by root, sys, or bin.</title>
      <discussion>NIS/NIS+/yp files are part of the system's identification and authentication processes and are, therefore, critical to system security.  Failure to give ownership of sensitive files or utilities to root or bin provides the designated owner and unauthorized users with the potential to access sensitive information or change the system configuration which could weaken the system's security posture.
      </discussion>
      <check_content>Perform the following to check NIS file ownership.
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      If the file ownership is not root, sys, or bin, this is a finding.</check_content>
      <fix_text>Change the ownership of NIS/NIS+/yp files to root, bin, or sys.

      Procedure:
      # chown -R root /usr/lib/netsvc/yp /var/yp</fix_text>

- name: V-789 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      </procedure>
      <output>
      V-789
      NIS/NIS+/yp files must be owned by root, sys, or bin.
      If the file ownership is not root, sys, or bin, this is a finding.
      Procedure:
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>NIS file ownership is root</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-789 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      </procedure>
      <output>
      V-789
      NIS/NIS+/yp files must be owned by root, sys, or bin.
      If the file ownership is not root, sys, or bin, this is a finding.
      Procedure:
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>NIS file ownership is NOT root</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-789 Fix-1
  file: path="{{item}}" owner=root
  with_items: "{{checkmyconf2.stdout_lines}}"
  when: (checkmyconf2.stdout != "" and FIX == 1)
