###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-800 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-800"
      rule_id="SV-800r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The /etc/shadow (or equivalent) file must have mode 0400.</title>
      <discussion>The /etc/shadow file contains the list of local system accounts.  It is vital to system security and must be protected from unauthorized modification.  The file also contains password hashes which must not be accessible to users other than root.</discussion>
      <check_content>Check the mode of the /etc/shadow file.
      # ls -lL /etc/shadow
      If the /etc/shadow file has a mode more permissive than 0400, this is a finding.</check_content>
      <fix_text>Change the mode of the /etc/shadow (or equivalent) file.
      # chmod &lt;mode&gt; &lt;file&gt;</fix_text>

- name: V-800 Check
  shell: ls -lL /etc/shadow
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-800 Check 2
  stat: path=/etc/shadow
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-800 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # ls -lL /etc/shadow
      </procedure>
      <output>
      V-800
      The /etc/shadow (or equivalent) file must have mode 0400.
      If the /etc/shadow file has a mode more permissive than 0400, this is a finding.
      Procedure:
      # ls -lL /etc/shadow
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      File Mode = {{checkmyconf2.stat.mode}}
      -
      This is NOT a finding
      -
      </output>
      <comments>the shadow file is not more permissive than 0400</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stat.mode == '0400' and REPORT == 1)

- name: V-800 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
     <procedure>
      Procedure: 
      # ls -lL /etc/shadow
      </procedure>
      <output>
      V-800
      The /etc/shadow (or equivalent) file must have mode 0400.
      If the /etc/shadow file has a mode more permissive than 0400, this is a finding.
      Procedure:
      # ls -lL /etc/shadow
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      File Mode = {{checkmyconf2.stat.mode}}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>the shadow file is more permissive than 0400</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stat.mode != '0400'

- name: V-800 Fix-1
  file: path=/etc/shadow mode=0400
  when: (checkmyconf2.stat.mode != '0400' and FIX == 1)
