###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22309 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22309"
      rule_id="SV-26353r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The root account's home directory must not have an extended ACL.</title>
      <discussion>File system extended ACLs provide access to files beyond what is allowed by the mode numbers of the files.</discussion>
      <check_content>Verify the root account's home directory has no extended ACL.
      # ls -ld ~root
      If the permissions include a "+", the directory has an extended ACL and this is a finding.</check_content>
      <fix_text>Remove the extended ACL from the directory.
      # chmod A- ~root</fix_text>

- name: V-22309 Check
  shell: ls -ld /root
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22309 Check 2
  shell: ls -ld /root | awk '!/\+/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22309 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22309
      The root account's home directory must not have an extended ACL.
      If the permissions include a "+", the directory has an extended ACL and this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>there are no ACLs on root's home directory </comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" and REPORT == 1)

- name: V-22309 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22309
      The root account's home directory must not have an extended ACL.
      If the permissions include a "+", the directory has an extended ACL and this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>there are ACLs on root's home directory </comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout == ""

- name: V-22309 Fix-1
  shell:  chmod A- ~root
  ignore_errors: True
  when: (checkmyconf2.stdout == "" and FIX == 1)
