###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-793 Check
  shell: find /usr/lib /lib /usr/sfw/lib -type f \( -perm -0022 -o -perm -0756 \) -exec ls -ld {} \;
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-793 Check 2
  shell: find /usr/lib /lib /usr/sfw/lib -type f \( -perm -0022 -o -perm -0756 \)
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-793 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-793"
      rule_id="SV-39821r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>Library files must have mode 0755 or less permissive.</title>
      <discussion>Unauthorized access could destroy the integrity of the library files.</discussion>
      <check_content>Check the mode of library files.

      Procedure:
      # ls -lLR /usr/lib /lib /usr/sfw/lib

      If any of the library files have a mode more permissive than 0755, this is a finding.
      </check_content>
      <fix_text>Change the mode of library files to 0755 or less permissive.

      Procedure (example):
      # chmod 0755 /path/to/library-file

      NOTE: Library files should have an extension of .a or .so, possibly followed by a version number.   </fix_text>

- name: V-793 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /usr/lib /lib /usr/sfw/lib -type f \( -perm -0022 -o -perm -0756 \)
      </procedure>
      <output>
      V-793
      Library files must have mode 0755 or less permissive.
      If any of the library files have a mode more permissive than 0755, this is a finding.
      Procedure:
      # find /usr/lib /lib /usr/sfw/lib -type f \( -perm -0022 -o -perm -0756 \)
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>No library files are more permissive than 0755</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>  
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-793 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /usr/lib /lib /usr/sfw/lib -type f \( -perm -0022 -o -perm -0756 \)
      </procedure>
      <output>
      V-793
      Library files must have mode 0755 or less permissive.
      If any of the library files have a mode more permissive than 0755, this is a finding.
      Procedure:
      # find /usr/lib /lib /usr/sfw/lib -type f \( -perm -0022 -o -perm -0756 \)
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>Library files are more permissive than 0755</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>  
  when: checkmyconf1.stdout != ""

- name: V-793 Fix
  file: path="{{item}}" mode=0755
  with_items: "{{checkmyconf2.stdout_lines}}"
  when: (checkmyconf1.stdout != "" and FIX == 1)
