###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-788 Check
  shell: find /etc/skel  -type f -perm -0645 -exec ls -ld {} \; 
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-788 Check 2
  shell: find /etc/skel  -type f -perm -0645 -exec ls -ld {} \; | awk '{print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-788 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-788"
      rule_id="SV-788r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All skeleton files (typically those in /etc/skel) must have mode 0644 or less permissive.</title>
      <discussion>If the skeleton files are not protected, unauthorized personnel could change user startup parameters and possibly jeopardize user files.

      </discussion>
      <check_content>Check skeleton files permissions.
      # ls -alL /etc/skel
      If a skeleton file has a mode more permissive than 0644, this is a finding.</check_content>
      <fix_text>Change the mode of skeleton files with incorrect mode.
      # chmod 0644 &lt;skeleton file&gt;</fix_text>

- name: V-788 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /etc/skel  -type f -perm -0645 -exec ls -ld {} \;
      </procedure>
      <output>  
      V-788
      All skeleton files (typically those in /etc/skel) must have mode 0644 or less permissive.
      If a skeleton file has a mode more permissive than 0644, this is a finding.
      Procedure:
      # find /etc/skel  -type f -perm -0645 -exec ls -ld {} \; 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>No skeleton files are more permissive than 0644</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-788 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /etc/skel  -type f -perm -0645 -exec ls -ld {} \;
      </procedure>
      <output>  
      V-788
      All skeleton files (typically those in /etc/skel) must have mode 0644 or less permissive.
      If a skeleton file has a mode more permissive than 0644, this is a finding.
      Procedure:
      # find /etc/skel  -type f -perm -0645 -exec ls -ld {} \; 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>Skeleton files are more permissive than 0644</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-788 Fix-1
  file: path="{{item}}" mode=0644
  with_items: "{{checkmyconf2.stdout_lines}}"
  when: (checkmyconf2.stdout != "" and FIX == 1)
