###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-778 Check
  shell: awk '/^CONSOLE/' /etc/default/login
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-778 Check 2
  shell: awk '/^CONSOLE=\/dev\/console/' /etc/default/login 
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-778 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-778"
      rule_id="SV-27143r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system must prevent the root account from directly logging in except from the system console.</title>
      <discussion>Limiting the root account direct logins to only system consoles protects the root account from direct unauthorized access from a non-console device.
      </discussion>
      <check_content>Check the CONSOLE setting in /etc/default/login
      # grep CONSOLE /etc/default/login
      If CONSOLE is set to a value other than /dev/console, this is a finding.</check_content>
      <fix_text>Edit the /etc/default/login file and uncomment the line containing /dev/console if it is commented out.</fix_text>

- name: V-778 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # awk '/^CONSOLE/' /etc/default/login
      </procedure>
      <output>
      V-778
      The system must prevent the root account from directly logging in except from the system console.
      If CONSOLE is set to a value other than /dev/console, this is a finding.
      Procedure:
      # awk '/^CONSOLE/' /etc/default/login
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>CONSOLE is set to /dev/console</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000770</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" and REPORT == 1)

- name: V-778 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # awk '/^CONSOLE/' /etc/default/login
      </procedure>
      <output>
      V-778
      The system must prevent the root account from directly logging in except from the system console.
      If CONSOLE is set to a value other than /dev/console, this is a finding.
      Procedure:
      # awk '/^CONSOLE/' /etc/default/login
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>CONSOLE is Not set to /dev/console</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000770</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout == ""

- name: V-778 Fix-1
  lineinfile: dest=/etc/default/login state=present regexp=CONSOLE line="CONSOLE=/dev/console"
  when: (checkmyconf2.stdout == "" and FIX == 1)
