###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22337 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22337"
      rule_id="SV-26433r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The /etc/group file must have mode 0644 or less permissive.</title>
      <discussion>The /etc/group file is critical to system security and must be protected from unauthorized modification.  The group file contains a list of system groups and associated information.</discussion>
      <check_content>Check the mode of the /etc/group file.

      Procedure:
      # ls -l /etc/group
      If the file mode is more permissive than 0644, this is a finding.</check_content>
      <fix_text>Change the mode of the /etc/group file to 0644 or less permissive.
      # chmod 0644 /etc/group</fix_text>

- name: V-22337 Check
  shell: ls -l /etc/group
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22337 Check 2
  stat: path=/etc/group
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22337 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22337
      The /etc/group file must have mode 0644 or less permissive.

      If the file mode is more permissive than 0644, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>/etc/group is not more permissive than 0644</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stat.mode == "0644" and REPORT == 1)

- name: V-22337 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22337
      The /etc/group file must have mode 0644 or less permissive.

      If the file mode is more permissive than 0644, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>/etc/group is MORE permissive than 0644</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stat.mode != "0644" )

- name: V-22337 Fix-1
  file: path=/etc/group group=root owner=root mode=0644 state=file
  ignore_errors: True
  when: (checkmyconf2.stat.mode != "0644" and FIX == 1)

