###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-11989 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-11989"
      rule_id="SV-40334r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The .rhosts file must not be supported in PAM.</title>
      <discussion>The .rhosts files are used to specify a list of hosts that are permitted remote access to a particular account without authenticating.  The use of such a mechanism defeats strong identification and authentication requirements.</discussion>
      <check_content>Check the PAM configuration for rhosts_auth.

      Procedure:
      # grep rhosts_auth /etc/pam.conf

      If a rhosts_auth entry is found that is not commented out, this is a finding.</check_content>
      <fix_text>Edit /etc/pam.conf and remove the reference(s) to the rhosts_auth module.
      </fix_text>


- name: V-11989 Check
  shell:  awk '/rhosts_auth/' /etc/pam.conf | awk '/!^#/'
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-11989 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-11989
      The .rhosts file must not be supported in PAM.
      If a rhosts_auth entry is found that is not commented out, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There is no rhosts_auth enter in /etc/pam.conf</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
      </finding>
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-11989 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-11989
      The .rhosts file must not be supported in PAM.
      If a rhosts_auth entry is found that is not commented out, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>There is an rhosts_auth enter in /etc/pam.conf</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
      </finding>
  when: checkmyconf1.stdout != ""

- name: V-11989 Fix
  replace: dest=/etc/pam.conf regexp="{{item}}" replace="#{{item}}"
  with_items: "{{ checkmyconf1.stdout_lines}}"
  when: (checkmyconf1.stdout != "" and FIX == 1)
