###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22334 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22334"
      rule_id="SV-26429r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The /etc/passwd file must not have an extended ACL.</title>
      <discussion>File system ACLs can provide access to files beyond what is allowed by the mode numbers of the files.  The /etc/passwd file contains the list of local system accounts. It is vital to system security and must be protected from unauthorized modification.</discussion>
      <check_content>Verify /etc/passwd has no extended ACL.
      # ls -l /etc/passwd
      If the permissions include a "+", the file has an extended ACL, this is a finding.</check_content>
      <fix_text>Remove the extended ACL from the file.
      # chmod A- /etc/passwd
      </fix_text>

- name: V-22334 Check
  shell: ls -l /etc/passwd
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22334 Check 2
  shell: ls -l /etc/passwd | awk '$1 ~ /\+/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22334 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22334
      The /etc/passwd file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There are not extended ACLs on /etc/passwd</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22334 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22334
      The /etc/passwd file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There are extended ACLs on /etc/passwd</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22334 Fix-1
  shell:  chmod A- /etc/passwd
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
