###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-11994 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-11994"
      rule_id="SV-27333r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>Crontabs must be owned by root or the crontab creator.</title>
      <discussion>To protect the integrity of scheduled system jobs and prevent malicious modification to these jobs, crontab files must be secured.</discussion>
      <check_content>List all crontabs on the system.  
      # ls -lL /var/spool/cron/crontabs/

      If any crontab is not owned by root or the creating user, this is a finding.</check_content>
      <fix_text>Change the crontab owner to root or the crontab creator.
      # chown root &lt;crontab file&gt;</fix_text>

- name: V-11994 Check
  shell: ls -lL /var/spool/cron/crontabs/
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-11994 Check 2
  shell: ls -lL /var/spool/cron/crontabs/ | awk '$3 !~ /root|^$/ {print "/var/spool/cron/crontabs/"$9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-11994 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-11994
      Crontabs must be owned by root or the crontab creator.
      If any crontab is not owned by root or the creating user, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>All crontabs are owned by root or their creating user</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-11994 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-11994
      Crontabs must be owned by root or the crontab creator.
      If any crontab is not owned by root or the creating user, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>NOT All crontabs are owned by root or their creating user</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-11994 Fix-1
  file: path="{{item}}" owner=root state=file 
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
