###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-792 Check
  shell: find /usr/share/man /usr/sfw/share/man /usr/sfw/man  -type f -perm -755 -exec ls -ld {} \;
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-792 Check 2
  shell: find /usr/share/man /usr/sfw/share/man /usr/sfw/man  -type f -perm -755 -exec ls -ld {} \; | awk '{print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-792 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-792"
      rule_id="SV-39835r1_rule"
      raw_risk="III"
      datetime="{{ ansible_date_time.date }}">
      <title>Manual page files must have mode 0644 or less permissive.</title>
      <discussion>If manual pages are compromised, misleading information could be inserted, causing actions that may compromise the system.</discussion>
      <check_content>Check the mode of the manual page files.
      Procedure: 
      # ls -lLR /usr/share/man /usr/sfw/share/man /usr/sfw/man

      If any of the manual page files have a mode more permissive than 0644, this is a finding.</check_content>
      <fix_text>Change the mode of manual page files to 0644 or less permissive.

      Procedure (example):
      # chmod 0644 &lt;path&gt;/&lt;manpage&gt;</fix_text>

- name: V-792 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
        Procedure: 
        # find /usr/share/man /usr/sfw/share/man /usr/sfw/man  -type f -perm -755 -exec ls -ld {} \;
      </procedure>
      <output>
        V-792
      Manual page files must have mode 0644 or less permissive.
      If any of the manual page files have a mode more permissive than 0644, this is a finding.
      Procedure:
      # find /usr/share/man /usr/sfw/share/man /usr/sfw/man  -type f -perm -755 -exec ls -ld {} \;
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>Man page files are not more permissive than 0644</comments>
      <status>Not a Finding</status>
      <ccis>
        <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-792 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
        Procedure: 
        # find /usr/share/man /usr/sfw/share/man /usr/sfw/man  -type f -perm -755 -exec ls -ld {} \;
      </procedure>
      <output>
        V-792
      Manual page files must have mode 0644 or less permissive.
      If any of the manual page files have a mode more permissive than 0644, this is a finding.
      Procedure:
      # find /usr/share/man /usr/sfw/share/man /usr/sfw/man  -type f -perm -755 -exec ls -ld {} \;
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>Man page files are more permissive than 0644</comments>
      <status>Ongoing</status>
      <ccis>
        <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-792 Fix-1
  file: path="{{item}}" mode=0644
  with_items: "{{checkmyconf2.stdout_lines}}"
  when: (checkmyconf2.stdout != "" and FIX == 1)
