###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22423 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22423"
      rule_id="SV-39884r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The inetd.conf file must be group-owned by root, bin, or sys.</title>
      <discussion>Failure to give ownership of sensitive files or utilities to system groups may provide unauthorized users with the potential to access sensitive information or change the system configuration which could weaken the system's security posture.</discussion>
      <check_content>Check the group ownership of the inetd.conf file.

      Procedure:
      # ls -alL /etc/inet/inetd.conf

      If the file is not group-owned by root, bin, or sys, this is a finding.</check_content>
      <fix_text>Change the group ownership of the inetd.conf file.
      Procedure:
      # chgrp sys /etc/inet/inetd.conf</fix_text>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>

- name: V-22423 Check
  shell: ls -alL /etc/inet/inetd.conf 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22423 Check 2
  shell: ls -alL /etc/inet/inetd.conf | awk '$4 !~ /root|bin|sys/ || $1 ~ /\+/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22423 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22423
      The inetd.conf file must be group-owned by root, bin, or sys.

      If the file is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>/etc/inet/inetd.conf is group owned by root</comments>
      <status>Not a Finding</status>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22423 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22423
      The inetd.conf file must be group-owned by root, bin, or sys.

      If the file is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>/etc/inet/inetd.conf is group owned by root</comments>
      <status>Ongoing</status>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22423 Fix-1
  file: path=/etc/inet/inetd.conf group=root state=file
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)

- name: V-22423 Fix-2
  shell: chmod A- /etc/inet/inetd.conf
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)

