###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22369 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22369"
      rule_id="SV-26502r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All system audit files must not have extended ACLs.</title>
      <discussion>If a user can write to the audit logs, then audit trails can be modified or destroyed and system intrusion may not be detected.</discussion>
      <check_content>Check the audit configuration to determine the location of the system audit log files.
      # more /etc/security/audit_control
      Check the system audit log files for extended ACLs.
      # ls -la [audit log dir]
      If the permissions include a "+", the file has an extended ACL and this is a finding.</check_content>
      <fix_text>Remove the extended ACL from the file. 
      # chmod A- [audit file]</fix_text>

- name: V-22369 Check
  shell: grep "^dir:" /etc/security/audit_control | awk "-F:" '{print $2}' | xargs ls -la 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22369 Check 2
  shell: grep "^dir:" /etc/security/audit_control | awk "-F:" '{print $2}' | xargs ls -la | awk '$1 ~ /\+/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22369 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22369
      All system audit files must not have extended ACLs.
      If the permissions include a "+", the file has an extended ACL and this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>No extended ACLs in /var/audit</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-00163</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22369 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22369
      All system audit files must not have extended ACLs.
      If the permissions include a "+", the file has an extended ACL and this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>Extended ACLs in /var/audit</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-00163</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22369 Fix-1
  shell:  chmod A- "{{item}}"
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
