###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22338 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22337"
      rule_id="SV-26433r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The /etc/group file must have mode 0644 or less permissive.</title>
      <discussion>The /etc/group file is critical to system security and must be protected from unauthorized modification.  The group file contains a list of system groups and associated information.</discussion>
      <check_content>Check the mode of the /etc/group file.

      Procedure:
      # ls -l /etc/group
      If the file mode is more permissive than 0644, this is a finding.</check_content>
      <fix_text>Change the mode of the /etc/group file to 0644 or less permissive.
      # chmod 0644 /etc/group</fix_text>

- name: V-22338 Check
  shell: ls -l /etc/group
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22338 Check 2
  shell: ls -l /etc/group | awk '$1 ~ /\+/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22338 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22338
      The /etc/group file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL and this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There are not extended ACLs on /etc/group</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22338 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22338
      The /etc/group file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL and this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>There ARE extended ACLs on /etc/group</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22338 Fix-1
  shell:  chmod A- /etc/group
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
