###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22375 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22375"
      rule_id="SV-40564r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The audit system must alert the SA when the audit storage volume approaches its capacity.</title>
      <discussion>An accurate and current audit trail is essential for maintaining a record of system activity.  If the system fails, the SA must be notified and must take prompt action to correct the problem.

      Minimally, the system must log this event and the SA will receive this notification during the daily system log review.  If feasible, active alerting (such as email or paging) should be employed consistent with the site’s established operations management systems and procedures.</discussion>
      <check_content>Verify the presence of an audit_warn entry in /etc/mail/aliases.

      # grep audit_warn /etc/mail/aliases

      If there is no audit_warn entry in /etc/mail/aliases, this is a finding.

      Verify the minfree parameter in /etc/security/audit_control.

      # egrep '^minfree:' /etc/security/audit_control

      If the minfree parameter is set to zero or not set at all, this is a finding.</check_content>
      <fix_text>If necessary, add an audit_warn alias to /etc/mail/aliases that will forward to designated system administrator(s).

      # vi /etc/mail/aliases

      Put the updated aliases file into service.

      # newaliases

      If necessary, add or update the minfree: parameter in /etc/security/audit_control.  

      # vi /etc/security/audit_control

      Ensure the minfree value is greater than zero and less than 100.</fix_text>

- name: V-22375 Check
  shell: grep audit_warn /etc/mail/aliases; egrep '^minfree:' /etc/security/audit_control
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22375 Check 2
  shell: egrep '^minfree:20' /etc/security/audit_control 
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22375 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22375
      The audit system must alert the SA when the audit storage volume approaches its capacity.
      If there is no audit_warn entry in /etc/mail/aliases, this is a finding.
      If the minfree parameter is set to zero or not set at all, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>audit_warn is configured in /etc/mail/aliases and minfree is set to a non-zero number</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000143</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" and REPORT == 1)

- name: V-22375 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22375
      The audit system must alert the SA when the audit storage volume approaches its capacity.
      If there is no audit_warn entry in /etc/mail/aliases, this is a finding.
      If the minfree parameter is set to zero or not set at all, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>audit_warn is NOT configured in /etc/mail/aliases and minfree is set to a non-zero number</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000143</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout == ""

- name: V-22375 Fix-1
  lineinfile: dest=/etc/security/audit_control state=present regexp=^minfree line="minfree:20"
  ignore_errors: True
  when: (checkmyconf2.stdout == "" and FIX == 1)
