###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22330 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22330"
      rule_id="SV-26422r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The /etc/nsswitch.conf file must not have an extended ACL.</title>
      <discussion>The nsswitch.conf file (or equivalent) configures the source of a variety of system security information including account, group, and host lookups.  Malicious changes could prevent the system from functioning or compromise system security.</discussion>
      <check_content>Verify /etc/nsswitch.conf has no extended ACL.

      Procedure:
      # ls -l /etc/nsswitch.conf
      If the permissions include a "+", the file has an extended ACL and this is a finding.</check_content>
      <fix_text>Remove the extended ACL from the file.
      # chmod A- /etc/nsswitch.conf</fix_text>

- name: V-22330 Check
  shell: ls -l /etc/nsswitch.conf 
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22330 Check 2
  shell: ls -l /etc/nsswitch.conf | awk '$1 ~ /\+/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22330 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22330
      The /etc/nsswitch.conf file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL and this is a finding.
      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There are not extended ACLs on /etc/nsswitch.conf </comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>

  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22330 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22330
      The /etc/nsswitch.conf file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL and this is a finding.
      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>There are extended ACLs on /etc/nsswitch.conf </comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22330 Fix-1
  shell:  chmod A- /etc/nsswitch.conf
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
