###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-794 Check
  shell: find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -006 -exec ls -ld {} \;; find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -060 -exec ls -ld {} \;
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-794 Check 2
  shell: find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -006 -exec ls -ld {} \; | awk '{print $9}'; find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -060 -exec ls -ld {} \; | awk '{print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-794 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-794"
      rule_id="SV-794r4_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All system command files must have mode 755 or less permissive.</title>
      <discussion>Restricting permissions will protect system command files from unauthorized modification. System command files include files present in directories used by the operating system for storing default system executables and files present in directories included in the system's default executable search paths.</discussion>
      <check_content>Check the permissions for files in /etc, /bin, /usr/bin, /usr/lbin, /usr/ucb, /sbin, and /usr/sbin.

      Procedure:
      # ls -lL /etc /bin /usr/bin /usr/lbin /usr/ucb /sbin /usr/sbin

      If any command file is listed and has a mode more permissive than 755, this is a finding.

      Note: Elevate to Severity Code I if any command file listed is world-writable.</check_content>
      <fix_text>Change the mode for system command files to 755 or less permissive.

      Procedure:
      # chmod 755 &lt;filename&gt;   </fix_text>

- name: V-794 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -006 -exec ls -ld {} \;; find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -060 -exec ls -ld {} \;
      </procedure>
      <output>
      V-794
      All system command files must have mode 0755 or less permissive.
      If any command file is listed and has a mode more permissive than 0755, this is a finding.
      Procedure:
      # find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -006 -exec ls -ld {} \;; find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -060 -exec ls -ld {} \;
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>System command files are not more permissive than 0755</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-794 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -006 -exec ls -ld {} \;; find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -060 -exec ls -ld {} \;
      </procedure>
      <output>
      V-794
      All system command files must have mode 0755 or less permissive.
      If any command file is listed and has a mode more permissive than 0755, this is a finding.
      Procedure:
      # find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -006 -exec ls -ld {} \;; find /etc /bin /usr/bin /usr/ucb /sbin /usr/sbin -type f -perm -060 -exec ls -ld {} \;
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>System command files are more permissive than 0755</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>
  when: checkmyconf1.stdout != ""

- name: V-794 Fix
  file: dest="{{item}}" mode=0755
  with_items: "{{checkmyconf2.stdout_lines}}"
  when: (checkmyconf2.stdout != "" and FIX == 1)

