###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22306 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22306"
      rule_id="SV-26324r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system must require at least eight characters be changed between the old and new passwords during a password change.</title>
      <discussion>To ensure password changes are effective in their goals, the system must ensure old and new passwords have significant differences.  Without significant changes, new passwords may be easily guessed based on the value of a previously compromised password.</discussion>
      <check_content>Check /etc/default/passwd to verify the MINDIFF setting. 

      # grep MINDIFF /etc/default/passwd

      If the setting is not present, or is less than 8, this is a finding.</check_content>
      <fix_text>Edit /etc/default/passwd and set or add a MINDIFF setting equal to or greater than 8.</fix_text>

- name: V-22306 Check
  shell: grep MINDIFF /etc/default/passwd 2>&1
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22306 Check 2
  shell: grep MINDIFF /etc/default/passwd 2>/dev/null | awk '/8/'
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22306 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22306
      The system must require at least eight characters be changed between the old and new passwords during a password change.
      If the setting is not present, or is less than 8, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>MINDIFF is at least 8</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000195</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "" and REPORT == 1)

- name: V-22306 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22306
      The system must require at least eight characters be changed between the old and new passwords during a password change.
      If the setting is not present, or is less than 8, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>MINDIFF is NOT SET to at least 8</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000195</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout == ""

- name: V-22306 Fix-1
  lineinfile: dest=/etc/default/passwd state=present regexp=MINDIFF line="MINDIFF=8"
  ignore_errors: True
  when: (checkmyconf2.stdout == "" and FIX == 1)
