###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22412 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22412"
      rule_id="SV-26626r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system must not apply reversed source routing to TCP responses.</title>
      <discussion>Source-routed packets allow the source of the packet to suggest that routers forward the packet along a different path than configured on the router, which can be used to bypass network security measures.</discussion>
      <check_content>Determine the type of zone that you are currently securing.
      # zonename

      If the zone is not the global zone, determine if any interfaces are exclusive to the zone:
      # dladm show-link

      If the output indicates "insufficient privileges" then this requirement is not applicable.

      If the zone is the global zone or the non-global zone has exclusive interfaces verify the system does not apply reversed source routing to TCP responses.

      # ndd /dev/tcp tcp_rev_src_routes

      If the result is not 0, this is a finding.</check_content>
      <fix_text>Configure the system to not apply reversed source routing to TCP responses.
      # ndd -set /dev/tcp tcp_rev_src_routes 0
      Also add this command to a system startup script.</fix_text>
      <ccis>
      <cci>CCI-001551</cci>
      </ccis>


- name: V-22412 Check
  shell: if [ $(zonename) = "global" ];   then ndd /dev/tcp tcp_rev_src_routes;   else echo "This is a zone and not applicable `zonename`"; fi
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22412 Check 2
  shell: if [ $(zonename) = "global" ];   then ndd /dev/tcp tcp_rev_src_routes;   else echo "0"; fi
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22412 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22412
      The system must not apply reversed source routing to TCP responses.
      If the zone is the global zone or the non-global zone has exclusive interfaces verify the system does not apply reversed source routing to TCP responses. 
      Procedure:
      # if [ $(zonename) = "global" ]
      #   then ndd /dev/tcp tcp_rev_src_routes
      #   else echo "This is a zone and not applicable `zonename`"
      # fi

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>ndd /dev/tcp tcp_rev_src_routes returns 0</comments>
      <status>Not a Finding</status>
      </finding>
  when: (checkmyconf2.stdout == "0" and REPORT == 1)

- name: V-22412 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22412
      The system must not apply reversed source routing to TCP responses.
      If the zone is the global zone or the non-global zone has exclusive interfaces verify the system does not apply reversed source routing to TCP responses. 
      Procedure:
      # if [ $(zonename) = "global" ]
      #   then ndd /dev/tcp tcp_rev_src_routes
      #   else echo "This is a zone and not applicable `zonename`"
      # fi

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>ndd /dev/tcp tcp_rev_src_routes returns 1</comments>
      <status>Ongoing</status>
      </finding>
  when: checkmyconf2.stdout != "0"

- name: V-22412 Fix-1
  shell: ndd -set /dev/tcp tcp_rev_src_routes 0 
  args:
    executable: /bin/bash
  ignore_errors: True
  when: (checkmyconf2.stdout != "0" and FIX == 1)
