###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22301 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22301"
      rule_id="SV-39865r1_rule"
      raw_risk="III"
      datetime="{{ ansible_date_time.date }}">
      <title>The system must display a publicly-viewable pattern during a graphical desktop environment session lock.</title>
      <discussion>To protect the on-screen content of a session, it must be replaced with a publicly-viewable pattern upon session lock. Examples of publicly viewable patterns include screen saver patterns, photographic images, solid colors, or a blank screen, so long as none of those patterns convey sensitive information.

      This requirement applies to graphical desktop environments provided by the system to locally attached displays and input devices, as well as, to graphical desktop environments provided to remote systems using remote access protocols.</discussion>
      <check_content>Determine if a publicly-viewable pattern is displayed during a session lock. If the session lock pattern is not publicly-viewable, this is a finding.

      Acceptable checks for settings.

      # grep -i dtsession /etc/dt/config/C/sys.resources | egrep -i "saverList|saverTimeout"

      The saverTimeout value should be 15 (see GEN000500).
      The saverList value of StartDtscreenBlank is an acceptable screensaver.</check_content>
      <fix_text>Edit the /etc/dt/config/C/sys.resources file and add/edit the following lines, using 15 for the saverTimeout, and using StartDtscreenBlank for the saverList.

      dtsession*saverTimeout:  15
      dtsession*saverList: StartDtscreenBlank</fix_text>


- name: V-22301 Check 
  shell: grep -i dtsession /etc/dt/config/C/sys.resources | egrep -i "saverList|saverTimeout" 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False


- name: V-22301 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]\>
      </procedure>
      <output> 
      V-22301
      The system must display a publicly-viewable pattern during a graphical desktop environment session lock.
      If the session lock pattern is not publicly-viewable, this is a finding.

      Desktops are not installed on this system and it is not possable to start one

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]\>-
      This is NOT a finding
      -
      </output>
      <comments>dtsession*saverTimeout: is set to 15</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000061</cci>
      </ccis>
      </finding>

