###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-787 Check
  shell: find /var/log /var/adm  -type f -perm -0641 -exec ls -ld {} \;
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-787 Check 2
  shell: find /var/log /var/adm  -type f -perm -0641 -exec ls -ld {} \; | awk '{print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-787 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-787"
      rule_id="SV-39832r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>System log files must have mode 0640 or less permissive.</title>
      <discussion>If the system log files are not protected, unauthorized users could change the logged data, eliminating its forensic value.</discussion>
      <check_content>Check the mode of log file hierarchies.

      Procedure:
      # ls -lLRa /var/log /var/adm

      If any of the log files or their directories have modes more permissive than "0640", and these are not documented, this is a finding.</check_content>
      <fix_text>Change the mode of the system log file(s) to 0640 or less permissive.

      Procedure:
      # chmod "0640" /path/to/system-log-file

      NOTE: Do not confuse system log files with audit logs.   Any subsystems that require less stringent permissions must be documented.</fix_text>

- name: V-787 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
        Procedure: 
        # find /var/log /var/adm  -type f -perm -0641 -exec ls -ld {} \; 
      </procedure>
      <output>
      V-787
      System log files must have mode 0640 or less permissive.
      If any of the log files or their directories have modes more permissive than "0640", and these are not documented, this is a finding.
      Procedure:
      # find /var/log /var/adm  -type f -perm -0641 -exec ls -ld {} \; 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>No log files or their directories have modes more permissive than 0640</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-001314</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-787 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
        Procedure: 
        # find /var/log /var/adm  -type f -perm -0641 -exec ls -ld {} \; 
      </procedure>
      <output>
      V-787
      System log files must have mode 0640 or less permissive.
      If any of the log files or their directories have modes more permissive than "0640", and these are not documented, this is a finding.
      Procedure:
      # find /var/log /var/adm  -type f -perm -0641 -exec ls -ld {} \; 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>Log files or their directories have modes more permissive than 0640</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-001314</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-787 Fix-1
  file: path="{{item}}" mode=0640
  with_items: "{{checkmyconf2.stdout_lines}}"
  when: (checkmyconf2.stdout != "" and FIX == 1)
