###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-791 Check
  shell: ls -lRa /usr/lib/netsvc/yp /var/yp
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-791 Check 2
  shell: find /usr/lib/netsvc/yp /var/yp -type f -perm -060 -exec ls -ld {} \; |awk '{print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-791 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-791"
      rule_id="SV-27175r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The NIS/NIS+/yp command files must have mode 0755 or less permissive.</title>
      <discussion>NIS/NIS+/yp files are part of the system's identification and authentication processes and are, therefore, critical to system security.  Unauthorized modification of these files could compromise these processes and the system.</discussion>
      <check_content>Perform the following to check NIS file mode.
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      If the file's mode is more permissive than 0755, this is a finding.</check_content>
      <fix_text>Change the mode of NIS/NIS+/yp command files to 0755 or less permissive.

      Procedure:
      # chmod -R 0755 /usr/lib/netsvc/yp /var/yp</fix_text>

- name: V-791 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      </procedure>
      <output>
      V-791
      The NIS/NIS+/yp command files must have mode 0755 or less permissive.
      If the file's mode is more permissive than 0755, this is a finding.
      Procedure:
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>NIS files are not more permissive than 0755</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-791 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      </procedure>
      <output>
      V-791
      The NIS/NIS+/yp command files must have mode 0755 or less permissive.
      If the file's mode is more permissive than 0755, this is a finding.
      Procedure:
      # ls -lRa /usr/lib/netsvc/yp /var/yp
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>NIS files are not more permissive than 0755</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-791 Fix-1
  file: path="{{item}}" mode=0755
  with_items: "{{checkmyconf2.stdout_lines}}"
  when: (checkmyconf2.stdout != "" and FIX == 1)

