###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22317 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22317"
      rule_id="SV-26377r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All library files must not have extended ACLs.</title>
      <discussion>Unauthorized access could destroy the integrity of the library files.</discussion>
      <check_content>Verify system libraries have no extended ACLs. 

      # ls -lL /usr/lib/* /lib/* /usr/sfw/lib

      If the permissions include a "+", the file has an extended ACL and this is a finding. 
      </check_content>
      <fix_text>Remove the extended ACL from the file.
      # chmod A- [file with extended ACL]</fix_text>

- name: V-22317 Check
  shell: ls -lL /usr/lib/* /lib/* /usr/sfw/lib | awk '$1 ~ /\+/'
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22317 Check 2
  shell: ls -lL /usr/lib/* /lib/* /usr/sfw/lib | awk '$1 ~ /\+/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22317 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22317
      All library files must not have extended ACLs.
      If the permissions include a "+", the file has an extended ACL and this is a finding. 

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There are no ACLs in /usr/lib/* /lib/* /usr/sfw/lib</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22317 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22317
      All library files must not have extended ACLs.
      If the permissions include a "+", the file has an extended ACL and this is a finding. 

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>There are ACLs in /usr/lib/* /lib/* /usr/sfw/lib</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22317 Fix-1
  shell:  chmod A- "{{item}}"
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
