###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22336 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22336"
      rule_id="SV-39899r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The /etc/group file must be group-owned by root, bin, or sys.</title>
      <discussion>The /etc/group file is critical to system security and must be protected from unauthorized modification.  The group file contains a list of system groups and associated information.</discussion>
      <check_content>Check the group ownership of the /etc/group file.

      Procedure:
      # ls -lL /etc/group

      If the file is not group-owned by root, bin, or sys, this is a finding.</check_content>
      <fix_text>Change the group owner of the /etc/group file.

      Procedure:
      # chgrp root /etc/group</fix_text>

- name: V-22336 Check
  shell: ls -l /etc/group
  args:
    executable: /bin/bash
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22336 Check 2
  shell: ls -l /etc/group | awk '$1 ~ /\+/ || $3 !~ /root/ || $4 !~ /root|bin|sys/ {print $9}'
  args:
    executable: /bin/bash
  register: checkmyconf2
  ignore_errors: True
  changed_when: False


- name: V-22336 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22336 
      The /etc/group file must be group-owned by root, bin, or sys.
      

      If the file is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>/etc/group is group owned by root </comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22336 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22336 
      The /etc/group file must be group-owned by root, bin, or sys.
      

      If the file is not group-owned by root, bin, or sys, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>/etc/group is NOT group owned by root </comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout != "")

- name: V-22336 Fix-1
  file: path=/etc/group group=root owner=root mode=0644 state=file
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)

