
###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- service: name=svc:/system/system-log:default state=started
- name: Closing XML File
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      </stig>
      </ansible>

- name: Send mail
  mail:
    host: localhost
    port: 25
    to: andrew.darley.ctr@navy.mil
    subject: Ansible-report
    body: 'System {{ ansible_hostname }} results are attached.'
    attach: "{{out_file}}"


# - shell: /audit/admin/cron/scap 
