###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-12049 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-12049"
      rule_id="SV-40811r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>Network analysis tools must not be installed.</title>
      <discussion>Network analysis tools allow for the capture of network traffic visible to the system.</discussion>
      <check_content>Determine if any network analysis tools are installed.

      Procedure:
      # find / -name ethereal
      # find / -name wireshark
      # find / -name tshark
      # find / -name netcat
      # find / -name tcpdump
      # find / -name snoop

      If any network analysis tools are found, this is a finding.</check_content>
      <fix_text>Remove the network analysis tool binary from the system. The snoop binary is part of the SUNWrcmdc package, which may also be removed if none of its components are required.

      Procedure:
      # rm &lt;binary&gt;
      # pkgrm SUNWrcmdc</fix_text>

- name: V-12049 Check
  shell: find /etc /usr /bin /sbin /export /opt /var /lib -name ethereal 2>/dev/null; find /etc /usr /bin /sbin /export /opt /var /lib -name wireshark 2>/dev/null; find /etc /usr /bin /sbin /export /opt /var /lib -name tshark 2>/dev/null; find /etc /usr /bin /sbin /export /opt /var /lib -name netcat 2>/dev/null; find /etc /usr /bin /sbin /export /opt /var /lib  -name tcpdump 2>/dev/null; find /etc /usr /bin /sbin /export /opt /var /lib  -name snoop 2>/dev/null
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-12049 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-12049
      Network analysis tools must not be installed.
      If any network analysis tools are found, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>No network analysis tools were found</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000305</cci>
      </ccis>
      </finding>
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-12049 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-12049
      Network analysis tools must not be installed.
      If any network analysis tools are found, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>Network analysis tools were found</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000305</cci>
      </ccis>
      </finding>
  when: checkmyconf1.stdout != ""
