###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22322 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22322"
      rule_id="SV-26402r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The /etc/resolv.conf file must not have an extended ACL.</title>
      <discussion>The resolv.conf (or equivalent) file configures the system's DNS resolver.  DNS is used to resolve host names to IP addresses.  If DNS configuration is modified maliciously, host name resolution may fail or return incorrect information.  DNS may be used by a variety of system security functions such as time synchronization, centralized authentication, and remote system logging.</discussion>
      <check_content>Verify /etc/resolv.conf has no extended ACL.
      # ls -l /etc/resolv.conf
      If the permissions include a "+", the file has an extended ACL, this is a finding.</check_content>
      <fix_text>Remove the extended ACL from the file.
      # chmod A- /etc/resolv.conf</fix_text>

- name: V-22322 Check
  shell: ls -l /etc/resolv.conf
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22322 Check 2
  shell: ls -l /etc/resolv.conf | awk '$1 ~ /\+/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22322 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22322
      The /etc/resolv.conf file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There are not extended ACLs on /etc/resolv.conf</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22322 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22322
      The /etc/resolv.conf file must not have an extended ACL.
      If the permissions include a "+", the file has an extended ACL, this is a finding.

      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>There are extended ACLs on /etc/resolv.conf</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22322 Fix-1
  shell:  chmod A- /etc/resolv.conf
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
