###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22357 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22357"
      rule_id="SV-26475r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>Skeleton files must not have extended ACLs.</title>
      <discussion>If the skeleton files are not protected, unauthorized personnel could change user's startup parameters and possibly jeopardize user's files.</discussion>
      <check_content>Check skeleton files for extended ACLs.
      # ls -alL /etc/skel
      If the permissions include a "+", the file has an extended ACL and this is a finding.</check_content>
      <fix_text>Remove the extended ACL from the file.
      # chmod A- [skeleton file with extended ACL]</fix_text>

- name: V-22357 Check
  shell: ls -lL /etc/skel 2>&1
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22357 Check 2
  shell: ls -lL /etc/skel 2>/dev/null | awk '/\+/ {print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22357 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output>    
      V-22357 
      Skeleton files must not have extended ACLs.
      If the permissions on an existing file include a "+", the file has an extended ACL, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>No ACLs are presnet in /etc/skel</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22357 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output>    
      V-22357 
      Skeleton files must not have extended ACLs.
      If the permissions on an existing file include a "+", the file has an extended ACL, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>ACLs ARE presnet in /etc/skel</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22357 Fix-1
  shell:  chmod A- "{{item}}"
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
