###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22363 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22363"
      rule_id="SV-26486r4_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>Local initialization files library search paths must contain only authorized paths.</title>
      <discussion>The library search path environment variable(s) contain a list of directories for the dynamic linker to search to find libraries. If this path includes the current working directory or other relative paths, libraries in these directories may be loaded instead of system libraries. This variable is formatted as a colon-separated list of directories. If there is an empty entry, such as a leading or trailing colon, two consecutive colons, or a single period, this is interpreted as the current working directory. Paths starting with a slash (/) are absolute paths.</discussion>
      <check_content>NOTE: This command should be used in the BASH shell.

      Verify local initialization files have library search path containing only authorized paths.
      # cut -d : -f 1 /etc/passwd | xargs -n1 -IUSER sh -c 'grep -l LD_LIBRARY_PATH ~USER/.*'

      This variable is formatted as a colon-separated list of directories.

      If there is an empty entry, such as a leading or trailing colon, or two consecutive colons, this is a finding.

      If an entry begins with a character other than a slash (/), or has not been documented with the ISSO, this is a finding.
      </check_content>
      <fix_text>Edit the local initialization file and remove the relative path entries from the library search path variables that have not been documented with the ISSO.  

      Edit the local initialization file and remove any empty entry that is defined.
      </fix_text>


- name: V-22363 Check
  shell: awk "-F:" '$3 > 100 && $7 !~ /false/ && $6 !~ /\/$/ && $1 !~ /ldap|root/  {print $4 " "$1 "  " $6}' /etc/passwd  | while read GRUP USER HOME;   do printf $HOME" "$USER" "$GRUP" ";   awk "-F:" '/'$USER'/ {print $3"|"var}' var=$GRUP /etc/group | paste -s -d\| -; done | while read HOME USER GRUP UGRP;   do find $HOME -exec ls -ld {} 2>/dev/null \;; done | awk '/\./ {print $9}' | while read DIR; do egrep 'LD_LIBRARY_PATH\=' $DIR ; done
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22363 Check 2
  shell: awk "-F:" '$3 > 100 && $7 !~ /false/ && $6 !~ /\/$/ && $1 !~ /ldap|root/  {print $4 " "$1 "  " $6}' /etc/passwd  | while read GRUP USER HOME;   do printf $HOME" "$USER" "$GRUP" ";   awk "-F:" '/'$USER'/ {print $3"|"var}' var=$GRUP /etc/group | paste -s -d\| -; done | while read HOME USER GRUP UGRP;   do find $HOME -exec ls -ld {} 2>/dev/null \;; done | awk '/\./ {print $9}' | while read DIR; do egrep 'LD_LIBRARY_PATH\=' $DIR ; done | awk '!/\=\$|\=\//'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22363 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22363 
      Local initialization files library search paths must contain only authorized paths.
      If there is an empty entry, such as a leading or trailing colon, or two consecutive colons, this is a finding. 
      If an entry begins with a character other than a slash (/), or has not been documented with the ISSO, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>LD_LIBRARY_PATH is not set in the local initialization files</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22363 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output>
      This is not fixed with Ansible 
      V-22363 
      Local initialization files library search paths must contain only authorized paths.
      If there is an empty entry, such as a leading or trailing colon, or two consecutive colons, this is a finding. 
      If an entry begins with a character other than a slash (/), or has not been documented with the ISSO, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>LD_LIBRARY_PATH is set in the local initialization files</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""
