###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-796 Check
  shell: find /etc /bin /usr/bin /usr/lbin /usr/ucb /sbin /usr/sbin -exec ls -ld {} \; | awk '$4 !~ /root|daemon|bin|sys|adm|tty|lp|uucp|mail|other|smmsp/'
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-796 Check 2
  shell: find /etc /bin /usr/bin /usr/lbin /usr/ucb /sbin /usr/sbin -exec ls -ld {} \; | awk '$4 !~ /root|daemon|bin|sys|adm|tty|lp|uucp|mail|other|smmsp/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-796 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-796"
      rule_id="SV-796r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>System files, programs, and directories must be group-owned by a system group.</title>
      <discussion>Restricting permissions will protect the files from unauthorized modification.</discussion>
      <check_content>Check the group ownership of system files, programs, and directories.

      Procedure:
      # ls -lLa /etc /bin /usr/bin /usr/lbin /usr/ucb /sbin /usr/sbin

      If any system file, program, or directory is not group-owned by a system group, this is a finding.</check_content>
      <fix_text>Change the group owner of system files to a system group.

      Procedure:
      # chgrp root /path/to/system/file

      (System groups other than root may be used.)   </fix_text>

- name: V-796 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /etc /bin /usr/bin /usr/lbin /usr/ucb /sbin /usr/sbin -exec ls -ld {} \; | awk '$4 !~ /root|daemon|bin|sys|adm|tty|lp|uucp|mail|other|smmsp/'
      </procedure>
      <output>
      V-796
      All system files, programs, and directories must be group-owned by a system account.
      If any of the system files, programs, or directories are not group-owned by a system account, this is a finding.
      Procedure:
      # find /etc /bin /usr/bin /usr/lbin /usr/ucb /sbin /usr/sbin -exec ls -ld {} \; | awk '$4 !~ /root|daemon|bin|sys|adm|tty|lp|uucp|mail|other|smmsp/'
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>All system files. program and directory are group owned by a system group</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-796 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /etc /bin /usr/bin /usr/lbin /usr/ucb /sbin /usr/sbin -exec ls -ld {} \; | awk '$4 !~ /root|daemon|bin|sys|adm|tty|lp|uucp|mail|other|smmsp/'
      </procedure>
      <output>
      V-796
      All system files, programs, and directories must be group-owned by a system account.
      If any of the system files, programs, or directories are not group-owned by a system account, this is a finding.
      Procedure:
      # find /etc /bin /usr/bin /usr/lbin /usr/ucb /sbin /usr/sbin -exec ls -ld {} \; | awk '$4 !~ /root|daemon|bin|sys|adm|tty|lp|uucp|mail|other|smmsp/'
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>Not all system files. program and directory are group owned by a system group</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>
  when: checkmyconf1.stdout != ""

- name: V-796 Fix
  file: dest="{{item}}" group=root
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)

