###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-11972 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-11972"
      rule_id="SV-27119r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>The system must require passwords to contain at least one numeric character.</title>
      <discussion>To enforce the use of complex passwords, minimum numbers of characters of different classes are mandated.  The use of complex passwords reduces the ability of attackers to successfully obtain valid passwords using guessing or exhaustive search techniques.  Complexity requirements increase the password search space by requiring users to construct passwords from a larger character set than they may otherwise use.</discussion>
      <check_content>Check the MINDIGIT setting.
      # grep MINDIGIT /etc/default/passwd
      If the MINDIGIT setting is less than 1, this is a finding.</check_content>
      <fix_text>Edit /etc/default/passwd and set the MINDIGIT setting to 1.</fix_text>


- name: V-11972 Check
  shell: awk '/MINDIGIT/' /etc/default/passwd 
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-11972 Check 2
  shell: awk '/MINDIGIT/' /etc/default/passwd 
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-11972 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-11972
      The system must require passwords to contain at least one numeric character.
      If the MINDIGIT setting is less than 1, this is a finding.
      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -  
      </output>
      <comments>MINDIGIT is set to greater to or equal to 1</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000194</cci>
      </ccis>
      </finding>

  when: (checkmyconf2.stdout != "" and REPORT == 1)

- name: V-11972 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-11972
      The system must require passwords to contain at least one numeric character.
      If the MINDIGIT setting is less than 1, this is a finding.
      <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} 
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>MINDIGIT is not set to greater to or equal to 1</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000194</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout == ""

- name: V-11972 Fix-1
  lineinfile: dest=/etc/default/passwd state=present regexp=MINDIGIT line="MINDIGIT=1"
  ignore_errors: True
  when: (checkmyconf2.stdout == "" and FIX == 1)
