###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-786 Check
  shell: find /usr/bin /usr/sbin -type f  -perm -022 -exec ls -ld {} \;
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-786 Check 2
  shell: find /usr/bin /usr/sbin -type f  -perm -022 -exec ls -ld {} \; | awk '{print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-786 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-786"
      rule_id="SV-27161r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All network services daemon files must have mode 0755 or less permissive.</title>
      <discussion>Restricting permission on daemons will protect them from unauthorized modification and possible system compromise.
      </discussion>
      <check_content>Check the mode of network services daemons.
      # ls -la /usr/bin /usr/sbin
      If the mode of a network services daemon is more permissive than 0755, this is a finding.
      NOTE: Network daemons not residing in these directories (such as httpd or sshd) must also be checked for the correct permissions.

      A way to locate network daemons, such as httpd and sshd, is with the ps command.
      # ps -ef | egrep '(sshd|httpd)'</check_content>
      <fix_text>Change the mode of the network services daemon.
      # chmod 0755 &lt;path&gt;</fix_text>

- name: V-786 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /usr/bin /usr/sbin -type f  -perm -022 -exec ls -ld {} \;
      </procedure>
      <output>
      V-786
      All network services daemon files must have mode 0755 or less permissive.
      If the mode of a network services daemon is more permissive than 0755, this is a finding.
      Procedure:
      # find /usr/bin /usr/sbin -type f  -perm -022 -exec ls -ld {} \;
      OUTPUT:
      ->  {{ checkmyconf1.stdout}}
      -
      This is NOT a finding
      -
      </output>
      <comments>no daemon permissions are more permissive than 0755</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-786 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      # find /usr/bin /usr/sbin -type f  -perm -022 -exec ls -ld {} \;
      </procedure>
      <output>
      V-786
      All network services daemon files must have mode 0755 or less permissive.
      If the mode of a network services daemon is more permissive than 0755, this is a finding.
      Procedure:
      # find /usr/bin /usr/sbin -type f  -perm -022 -exec ls -ld {} \;
      OUTPUT:
      ->  {{ checkmyconf1.stdout}}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>A daemon permissions are more permissive than 0755</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-000225</cci>
      </ccis>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-786 Fix-1
  file: path="{{item}}" mode=0755
  with_items: "{{checkmyconf2.stdout_lines}}"
  when: (checkmyconf2.stdout != "" and FIX == 1)
