###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-795 Check
  shell: awk "-F:" '$3 <150 {print $1}' /etc/group | paste -s -d'|' - | while read SYSACCOUNTS; do find /etc /bin /usr/bin /usr/local/bin /sbin /usr/sbin /usr/local/sbin -exec ls -ld {} \; | awk '$3 !~ /'$SYSACCOUNTS'/'; done
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-795 Check 2
  shell: awk "-F:" '$3 <150 {print $1}' /etc/group | paste -s -d'|' - | while read SYSACCOUNTS; do find /etc /bin /usr/bin /usr/local/bin /sbin /usr/sbin /usr/local/sbin -exec ls -ld {} \; | awk '$3 !~ /'$SYSACCOUNTS'/'; done | awk '{print $9}'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-795 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-795"
      rule_id="SV-795r2_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>All system files, programs, and directories must be owned by a system account.</title>
      <discussion>Restricting permissions will protect the files from unauthorized modification.</discussion>
      <check_content>Check the ownership of system files, programs, and directories.

      Procedure:
      # ls -lLa /etc /bin /usr/bin /usr/lbin /usr/ucb /sbin /usr/sbin

      If any of the system files, programs, or directories are not owned by a system account, this is a finding.</check_content>
      <fix_text>Change the owner of system files, programs, and directories to a system account.

      Procedure:
      # chown root /some/system/file

      (A different system user may be used in place of root.)   </fix_text>


- name: V-795 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      awk "-F:" '$3 &lt;150 {print $1}' /etc/group | paste -s -d'|' - | while read SYSACCOUNTS; do find /etc /bin /usr/bin /usr/local/bin /sbin /usr/sbin /usr/local/sbin -exec ls -ld {} \; | awk '$3 !~ /'$SYSACCOUNTS'/'; done
      </procedure>
      <output>
      V-795
      All system files, programs, and directories must be owned by a system account.
      If any of the system files, programs, or directories are not owned by a system account, this is a finding.
      Procedure:
      # awk "-F:" '$3 &lt;150 {print $1}' /etc/group | paste -s -d'|' - | while read SYSACCOUNTS; do find /etc /bin /usr/bin /usr/local/bin /sbin /usr/sbin /usr/local/sbin -exec ls -ld {} \; | awk '$3 !~ /'$SYSACCOUNTS'/'; done
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      -
      This is NOT a finding
      -
      </output>
      <comments>All system files. program and directory are group owned by a system group</comments>
      <status>Not a Finding</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>
  when: (checkmyconf1.stdout == "" and REPORT == 1)

- name: V-795 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure>
      Procedure: 
      awk "-F:" '$3 &lt;150 {print $1}' /etc/group | paste -s -d'|' - | while read SYSACCOUNTS; do find /etc /bin /usr/bin /usr/local/bin /sbin /usr/sbin /usr/local/sbin -exec ls -ld {} \; | awk '$3 !~ /'$SYSACCOUNTS'/'; done
      </procedure>
      <output>
      V-795
      All system files, programs, and directories must be owned by a system account.
      If any of the system files, programs, or directories are not owned by a system account, this is a finding.
      Procedure:
      # awk "-F:" '$3 &lt;150 {print $1}' /etc/group | paste -s -d'|' - | while read SYSACCOUNTS; do find /etc /bin /usr/bin /usr/local/bin /sbin /usr/sbin /usr/local/sbin -exec ls -ld {} \; | awk '$3 !~ /'$SYSACCOUNTS'/'; done
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ====================================================================
      This is a FINDING
      -
      </output>
      <comments>Not all system files. program and directory are group owned by a system group</comments>
      <status>Ongoing</status>
      <ccis>
      <cci>CCI-001499</cci>
      </ccis>
      </finding>
  when: checkmyconf1.stdout != ""

- name: V-795 Fix
  file: dest="{{item}}" owner=root group=root
  with_items: "{{checkmyconf2.stdout_lines}}"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
