###############################################
# Developed For 7.2.4 by Andrew Darley     
#     andrew.darley.ctr@navy.mil  
#      
# Originally created for:
# Solaris 10 x86/SPARC Manual STIG - Ver 1
# Release: 19 Benchmark Date: 28 Jul 2017
# 
# This is expected to run with a play book that
# defines these variables
# output_path
# out_file
# FIX
###############################################


- name: V-22404 Finding Open Tags
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <finding
      v_id="V-22404"
      rule_id="SV-26605r1_rule"
      raw_risk="II"
      datetime="{{ ansible_date_time.date }}">
      <title>Kernel core dumps must be disabled unless needed.</title>
      <discussion>Kernel core dumps may contain the full contents of system memory at the time of the crash.  Kernel core dumps may consume a considerable amount of disk space and may result in Denial of Service by exhausting the available space on the target file system.  The kernel core dump process may increase the amount of time a system is unavailable due to a crash.  Kernel core dumps can be useful for kernel debugging.</discussion>
      <check_content>Verify savecore is not used.
      # dumpadm | grep 'Savecore enabled'
      If the value is true, this is a finding.

      OR

      # grep DUMPADM_ENABLE /etc/dumpadm.conf
      If the value is yes, this is a finding.</check_content>
      <fix_text>Disable savecore.
      # dumpadm -n</fix_text>
      <ccis>
      <cci>CCI-000366</cci>
      </ccis>

- name: V-22404 Check
  shell: grep DUMPADM_ENABLE /etc/dumpadm.conf
  register: checkmyconf1
  ignore_errors: True
  changed_when: False

- name: V-22404 Check 2
  shell: grep DUMPADM_ENABLE /etc/dumpadm.conf | awk "-F=" '$2 ~ /yes/'
  register: checkmyconf2
  ignore_errors: True
  changed_when: False

- name: V-22404 Pass
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22404
      Kernel core dumps must be disabled unless needed.
      If the value is yes, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>-
      This is NOT a finding
      -
      </output>
      <comments>savecore is disabled not a finding.</comments>
      <status>Not a Finding</status>
      </finding>
  when: (checkmyconf2.stdout == "" and REPORT == 1)

- name: V-22404 Fail
  blockinfile:
    dest: "{{out_file}}"
    state: present
    marker: " "
    block: |
      <procedure> <![CDATA[
      Procedure: 
      # {{ checkmyconf1.cmd }} ]]>
      </procedure>
      <output> 
      V-22404
      Kernel core dumps must be disabled unless needed.
      If the value is yes, this is a finding.

      <![CDATA[
      OUTPUT:
      ->  {{ checkmyconf1.stdout }}
      ]]>====================================================================
      This is a FINDING
      -
      </output>
      <comments>savecore is disabled not a finding.</comments>
      <status>Ongoing</status>
      </finding>
  when: checkmyconf2.stdout != ""

- name: V-22404 Fix-1
  lineinfile: dest=/etc/dumpadm.conf state=present regexp=^DUMPADM_ENABLE line="DUMPADM_ENABLE=no"
  ignore_errors: True
  when: (checkmyconf2.stdout != "" and FIX == 1)
